const images = {
    harry1: require('./harry1.jpg').default,
    azkaban: require('./azkaban.jpg').default,
    beautiful: require('./beautiful.jpg').default,
    before: require('./before.jpg').default,
    brief: require('./brief.jpg').default,
    caged: require('./caged.jpg').default,
    circus: require('./circus.jpg').default,
    cot: require('./cot.jpg').default,
    deathly: require('./deathly.jpg').default,
    deep: require('./deep.jpg').default,
    fault: require('./fault.jpg').default,
    freakonomics: require('./freakonomics.jpg').default,
    goblet: require('./goblet.jpg').default,
    hiroshima: require('./hiroshima.jpg').default,
    indian: require('./indian.jpg').default,
    kind: require('./kind.jpg').default,
    long: require('./long.jpg').default,
    rabbit: require('./rabbit.jpg').default,
    remote: require('./remote.jpg').default,
    room: require('./room.jpg').default,
    saints: require('./saints.jpg').default,
    sapiens: require('./sapiens.jpg').default,
    silent: require('./silent.jpg').default,
    simple: require('./simple.jpg').default,
    sss: require('./sss.jpg').default,
    storm: require('./storm.jpg').default,
    teeth: require('./teeth.jpg').default,
    tell: require('./tell.jpg').default,
    misery: require('./misery.jpg').default,
    stuntboy: require('./stuntboy.jpg').default,
    less: require('./less.jpg').default,
    idiots: require('./idiots.jpg').default,
    forward: require('./forward.jpg').default,
    wicked: require('./wicked.jpg').default,
};

export default images;
